plugins { id 'com.android.application' }

android {
    namespace 'com.tian.gametranslator'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tian.gametranslator'
        minSdk 23
        targetSdk 35
        versionCode 7
        versionName '0.7.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition:16.0.1'
    implementation 'com.google.mlkit:translate:17.0.3'
}
